name: unseen-object-clustering
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.11.0
  - pytorch-mutex=1.0=cuda
  - cudatoolkit=10.2

  - python=3.8
  - torchvision
  - pcl=1.9
  - cython

  - pip

  - pip:
    - opencv-python == 4.2.0.34
    - transforms3d
    - pillow
    - IPython
    - matplotlib
    - easydict
    - pyyaml
    - future
    - scipy
    - imageio
    # - python-pcl
    - gdown
